### ISSUE TITLE
Find a definitive name for the component

### ISSUE THREAD

**Issue by psotres** [Sedimark/dlt-connector-rs#1]
We should try to find a definitive name for this component within SEDIMARK. There is a dataspace connector component in the SEDIMARK participant toolbox that will be relying in this one for offloading crypto operations and carry out identity management. 

Possible options:

- DLT Connector &rarr; dataspace connector can be SEDIMARK EDC Connector.
- Wallet &rarr; more generic option
- ...

**Comment by psotres** [comment]
Some extra ideas courtesy of copilot:
- DLTWallet
- CryptoVault
- SecureEnabler
- DLTEnabler :-)
- StrongholdHub
- SecureLink
- CipherNode
- DLTGuard
- CryptoInterface (generic... not bad)
- ...and many more

**Comment by xamcost** [comment]
Swinging by this issue, a few suggestion based on the themes of bees/hornets that IOTA seems to enjoy:
- VespaNode
- BeeWings
- Alveolus
- (Bee/Hornet/Vespa)Swarm

**Comment by psotres** [comment]
Won't be the one choosing the name, but I'd rather go with a generic name instead of a commercial one. Something like "Trust manager" that can fit whatever we end up doing with the component.
